# Log to timeseries
Here you can learn more use of tensor in time series data.<br/>
This tutorial mainly introduces how to transfer other forms of data, e.g.: log, to timeseries data.

Import spartan package.<br/>
Remember to install spartan from pip or clone the project from github before doing this.

In [1]:
import spartan as st

Using backend cpu

Load data by function ```loadTensor```.<br/>

In [2]:
tensor_data = st.loadTensor(path="./inputData/wbcovid19_test.gz", sep='')
print(tensor_data.data)

                        0     1                 2    3         4
0     2020-01-11 16:58:12     0  4459592174140754    0     79984
1     2020-01-11 16:58:12     1  4459592174142932    1   6836725
2     2020-01-11 16:58:13     2  4459592177709460    1   6836725
3     2020-01-11 16:58:13     3  4459592177714275    2    104668
4     2020-01-11 16:58:13     4  4459592177715067    2    104668
...                   ...   ...               ...  ...       ...
9995  2020-01-11 18:01:00  9527  4459607973534612  502   9451393
9996  2020-01-11 18:00:59  9528  4459607973768695  509      6537
9997  2020-01-11 18:01:00  9529  4459607977732182    0     79984
9998  2020-01-11 18:01:01  9530  4459607981947099  380     79984
9999  2020-01-11 18:01:01  9531  4459607981954389  492  12837383

[10000 rows x 5 columns]

Use ```log_to_time``` function to transfer log into time series data.<br/>

In [3]:
tensor_data.log_to_time(range=(10, 20), group_col=[1], inplace=True)

c:\Users\bailean\AppData\Local\Programs\Python\Python310\lib\site-packages\spartan\tensor\tensor.py:114: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (1 levels on the left, 2 on the right)
  _ans = time_df.join(grouped_data, on=time_col, how='outer')

In [4]:
tensor_data.data

,0,"(2, 10)","(2, 11)","(2, 12)","(2, 13)","(2, 14)","(2, 15)","(2, 16)","(2, 17)","(2, 18)",...,"(4, 10)","(4, 11)","(4, 12)","(4, 13)","(4, 14)","(4, 15)","(4, 16)","(4, 17)","(4, 18)","(4, 19)"
0,1.578791e+09,4.459592e+15,4.459592e+15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10120178.0,22519430.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.578791e+09,NaN,NaN,4.459592e+15,4.459592e+15,4.459592e+15,4.459592e+15,4.459592e+15,NaN,NaN,...,NaN,NaN,2094687.0,21405106.0,29033754.0,2328656.0,12163145.0,NaN,NaN,NaN
6,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.459592e+15,4.459592e+15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36305711.0,18917446.0,25286000.0
10,1.578791e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Transfer to DTensor, designed for time series, by function ```toDTensor```.<br/>
Create Timeseries object by calling init function ```st.Timeseries```.

In [5]:
time, value = tensor_data.toDTensor(hastticks=True)
time_series = st.Timeseries(value, time, labels = tensor_data.labels)
print(time_series)

            Time       (2, 10)       (2, 11)       (2, 12)       (2, 13)  \
0   1.578791e+09  4.459592e+15  4.459592e+15           NaN           NaN
1   1.578791e+09           NaN           NaN           NaN           NaN
2   1.578791e+09           NaN           NaN           NaN           NaN
3   1.578791e+09           NaN           NaN           NaN           NaN
4   1.578791e+09           NaN           NaN           NaN           NaN
5   1.578791e+09           NaN           NaN  4.459592e+15  4.459592e+15
6   1.578791e+09           NaN           NaN           NaN           NaN
7   1.578791e+09           NaN           NaN           NaN           NaN
8   1.578791e+09           NaN           NaN           NaN           NaN
9   1.578791e+09           NaN           NaN           NaN           NaN
10  1.578791e+09           NaN           NaN           NaN           NaN

         (2, 14)       (2, 15)       (2, 16)       (2, 17)       (2, 18)  ...  \
0            NaN           NaN           NaN           NaN           NaN  ...
1            NaN           NaN           NaN           NaN           NaN  ...
2            NaN           NaN           NaN           NaN           NaN  ...
3            NaN           NaN           NaN           NaN           NaN  ...
4            NaN           NaN           NaN           NaN           NaN  ...
5   4.459592e+15  4.459592e+15  4.459592e+15           NaN           NaN  ...
6            NaN           NaN           NaN           NaN           NaN  ...
7            NaN           NaN           NaN           NaN           NaN  ...
8            NaN           NaN           NaN           NaN           NaN  ...
9            NaN           NaN           NaN  4.459592e+15  4.459592e+15  ...
10           NaN           NaN           NaN           NaN           NaN  ...

       (4, 10)     (4, 11)    (4, 12)     (4, 13)     (4, 14)    (4, 15)  \
0   10120178.0  22519430.0        NaN         NaN         NaN        NaN
1          NaN         NaN        NaN         NaN         NaN        NaN
2          NaN         NaN        NaN         NaN         NaN        NaN
3          NaN         NaN        NaN         NaN         NaN        NaN
4          NaN         NaN        NaN         NaN         NaN        NaN
5          NaN         NaN  2094687.0  21405106.0  29033754.0  2328656.0
6          NaN         NaN        NaN         NaN         NaN        NaN
7          NaN         NaN        NaN         NaN         NaN        NaN
8          NaN         NaN        NaN         NaN         NaN        NaN
9          NaN         NaN        NaN         NaN         NaN        NaN
10         NaN         NaN        NaN         NaN         NaN        NaN

       (4, 16)     (4, 17)     (4, 18)     (4, 19)
0          NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN
5   12163145.0         NaN         NaN         NaN
6          NaN         NaN         NaN         NaN
7          NaN         NaN         NaN         NaN
8          NaN         NaN         NaN         NaN
9          NaN  36305711.0  18917446.0  25286000.0
10         NaN         NaN         NaN         NaN

[11 rows x 31 columns]

            Time Series Object
            Dimension Size: 30
            Length: 11
            Time Length: 2.0
            Frequency: 5.5
            Start Timestamp: 1578790694.0
            Labels: (2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (2, 16), (2, 17), (2, 18), (2, 19), (3, 10), (3, 11), (3, 12), (3, 13), (3, 14), (3, 15), (3, 16), (3, 17), (3, 18), (3, 19), (4, 10), (4, 11), (4, 12), (4, 13), (4, 14), (4, 15), (4, 16), (4, 17), (4, 18), (4, 19)